### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by kocane** [KevinWang15/rutorrent-auto-delete#1]
Sweet script @KevinWang15, works a charm. Much easier than pyroscope/pyrocore.

That was all.

**Comment by KevinWang15** [comment]
You are welcome :)

You may want to check this one out:
https://github.com/KevinWang15/seedbox-bot

It's my latest seedbox management bot, it supports rutorrent and has many more powerful features.

@kocane

**Comment by kocane** [comment]
@KevinWang15 Sweet, even better! :-) Thanks
